vich_uploader:
    db_driver: orm

    mappings:
        post_images:
            uri_prefix:  '%app.path.post_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.post_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        author_avatars:
            uri_prefix:  '%app.path.author_avatars%'
            upload_destination: '%kernel.project_dir%/public%app.path.author_avatars%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
